from pathlib import Path
from textwrap import dedent

from util.exceptions import CustomException

from execution.frame import Frame
from configuration.diagrams import Diagram


# Symbolic Sequences

SYMBOLS = ["A", "B", "C", "D"]


def process_simple_symbolic(frame: Frame):
    cycles = []

    with open(get_symbolic_raw_file(frame)) as raw_file:
        for line in raw_file:
            period = 0
            num_symbols = {symbol: 0 for symbol in SYMBOLS}

            for char in line:
                if char in SYMBOLS:
                    period += 1
                    num_symbols[char] += 1

            cycle = f"Period {period:3d}    "
            for symbol in SYMBOLS:
                cycle += f"{symbol}{num_symbols[symbol]:2d}  "
            cycle = cycle[:-2]

            cycles.append(cycle)

    cycles = {cycle for cycle in cycles}  # filter duplicated

    with open(get_symbolic_target_file(frame), "w") as target_file:
        target_file.write(
            dedent(
                f"""Coexisting cycles: {len(cycles)}
                
                """
            )
        )

        for n, cycle in enumerate(cycles):
            target_file.write(f"{n:2d}: {cycle}\n")

        target_file.write(
            dedent(
                f"""

                # This file is automatically generated
                # Assumption: The cycles always are of the form Ax By Cz Dn
                """
            )
        )


def process_symbolic(diagram: Diagram):
    if diagram.animation != None:
        print("Symbolic Sequence not yet supported for animation")
        return


# Paths


def get_symbolic_raw_file(frame: Frame) -> Path:
    return frame.path / "periodic_symbolic_sequence.tna"


def get_symbolic_target_file(frame: Frame) -> Path:
    return frame.diagram.path / "symbolic.txt"
