name: Build Report

on:
  push:
    branches:
      - develop
    tags:
      - v*

env:
  DOC_SOURCE: Report/Masterarbeit_Weik.tex
  DOC_TARGET: Report/Masterarbeit_Weik.pdf
  DECLARATION: Report/declaration.pdf
  TMP_SIGNED_DOC: Report/Masterarbeit_Weik_signed.pdf

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3

      - name: Install qpdf
        run: |
          sudo apt-get update
          sudo apt-get install qpdf

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: "${{ env.DOC_SOURCE }}"

      - name: Add Assurance
        run: |
          qpdf --empty --pages "${DOC_TARGET}" 1-r2 "${DECLARATION}" -- "${TMP_SIGNED_DOC}"
          mv "${TMP_SIGNED_DOC}" "${DOC_TARGET}"

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.DOC }}.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
