name: Build Report

on:
  push:
    branches:
      - develop
      - feature/ci
    tags:
      - v*

env:
  DOCUMENT_NAME: Report/Masterarbeit_Weik

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "${{ env.DOCUMENT_NAME }}.tex"
          
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.DOCUMENT_NAME }}.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}