name: Build Report

on:
  push:
    branches:
      - develop
    tags:
      - v*

env:
  DOCUMENT_NAME: Report/Masterarbeit_Weik

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3
      
      - run: ls Report/Figures/FareyTrees/Minrep_Adding1_Halved

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: "${{ env.DOCUMENT_NAME }}.tex"
          
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.DOCUMENT_NAME }}.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
