name: Build Report

on:
  push:
    branches:
      - develop
    tags:
      - v*

env:
  DOC_SOURCE: Report/Masterarbeit_Weik.tex
  DOC_TARGET: Report/Masterarbeit_Weik.pdf
  DECLARATION: Report/declaration.pdf
  TMP_SIGNED_DOC: Report/Masterarbeit_Weik_signed.pdf
  CODE_ARCHIVE: Masterarbeit_Weik_SourceCode.tar.gz
  CODE_ARCHIVE_PICS: Masterarbeit_Weik_SourceCode_WithPictures.tar.gz
  SUBMISSION: Masterarbeit_Weik_Submission.tar.gz

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Package source code
        run: ./archive_source_code.sh

      - name: Install qpdf
        run: |
          sudo apt-get update
          sudo apt-get install qpdf

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: "${{ env.DOC_SOURCE }}"

      - name: Add assurance
        run: |
          qpdf --empty --pages "${DOC_TARGET}" 1-r2 "${DECLARATION}" -- "${TMP_SIGNED_DOC}"
          mv "${TMP_SIGNED_DOC}" "${DOC_TARGET}"
          
      - name: Package submission
        run: ./package_everything.sh

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.DOC_TARGET }},${{ env.CODE_ARCHIVE }},${{ env.CODE_ARCHIVE_PICS }}"
          token: ${{ secrets.GITHUB_TOKEN }}
