name: Build Report

on:
  push:
    branches:
      - develop
    tags:
      - v*

env:
  DOC_SOURCE: Report/Masterarbeit_Weik.tex
  DOC_TARGET: Report/Masterarbeit_Weik.pdf
  TMP_SIGNED_DOC: Report/Masterarbeit_Weik_signed.pdf
  CODE_ARCHIVE: Masterarbeit_Weik_SourceCode.tar.gz
  CODE_ARCHIVE_PICS: Masterarbeit_Weik_SourceCode_WithPictures.tar.gz
  ABSTRACT: abstract.txt
  ZUSAMMENFASSUNG: zusammenfassung.txt

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Package source code
        run: ./archive_source_code.sh

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: "${{ env.DOC_SOURCE }}"

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.ABSTRACT }},${{ env.ZUSAMMENFASSUNG }},${{ env.DOC_TARGET }},${{ env.CODE_ARCHIVE }},${{ env.CODE_ARCHIVE_PICS }}"
          token: ${{ secrets.GITHUB_TOKEN }}
